on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.8'
      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.15.8'
      - shell: bash
        run: mkdir -p "$HOME/.config/astra"
      - shell: bash
        env:
          SA: ${{ secrets.ASTRA_SERVICE_ACCOUNT }}
        run: |
          echo "$SA" > "$HOME/.config/astra/sa.json"
      - name: Lint
        run: go test -v ./...
